---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть протестирован на совместимость с предпоследними версиями браузеров на PC.
  - Сайт должен быть протестирован на совместимость с последними и предпоследними версиями браузеров на мобильных устройствах с IOS и AndrPoid.
  - Компьютер, на котором расположен сайт, должен иметь железо и подключение к сети, способное поддерживать большое количество трафика.
  - Пользователь должен иметь возможность искать любые (из имеющихся на сайте) товары с помощью фильтров независимо от пагинации.
  - Пользователь должен иметь возможность просмотреть текстовое описание товара, имеющего подробные характеристики, например, цвет, вес, габариты, ёмкость и т.д.
  - Пользователь должен иметь возможность фильтровать товары по рейтингу.
  - Пользователь должен иметь возможность сбросить фильтры.
  - Пользователь должен иметь возможность сразу указать количество того или иного товара при добавлении в корзину.
  - В корзине должны отображаться корректные выбранные пользователем товары в количестве соответствующем, выбору пользователя.
  - Пользователь должен иметь возможность удалять товары из корзины и очищать корзину полностью.
  - Фильтрация товаров по цене должна учитывать цены товаров с учетом имеющихся скидок.
  - Пользователь должен иметь возможность переключать язык сайта.